fitnessProject/fitnessApp/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.fitness_profile, name='fitness_profile'),
]

fitnessProject/fitnessProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("", include("fitnessApp.urls")),
    path('admin/', admin.site.urls),
]

fitnessProject/fitnessApp/models.py
from django.db import models

# Create your models here.
from django.db import models

class FitnessProfile(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    height = models.FloatField()
    weight = models.FloatField()
    goal = models.IntegerField()
    activity_level = models.IntegerField()
    time_commitment = models.IntegerField()
    calorie_target = models.IntegerField()
    protein = models.IntegerField()
    carbs = models.IntegerField()
    fats = models.IntegerField()
    program = models.CharField(max_length=255)

fitnessProject/fitnessApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import FitnessProfile

def fitness_profile(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        age = int(request.POST.get('age'))
        height = float(request.POST.get('height'))
        weight = float(request.POST.get('weight'))
        goal = int(request.POST.get('goal'))
        activity_level = int(request.POST.get('activity_level'))
        time_commitment = int(request.POST.get('time_commitment'))

        # Calculate BMR
        bmr = 88.362 + (13.397 * (weight / 2.205)) + (4.799 * (height * 2.54))

        # Initialize variables
        percent_bmr_change = 0
        activity_level_change = 0
        calorie_target = 0
        protein_adjustment = 0
        carb_adjustment = 0
        fat_adjustment = 0

        # Change percent_bmr_change based on user input
        if goal == 1:
            percent_bmr_change = 0.9
        elif goal == 2:
            percent_bmr_change = 1.2
        elif goal == 3:
            percent_bmr_change = 1

        # Change activity_level_change based on user input
        if activity_level == 0:
            activity_level_change = percent_bmr_change - 0.05
        elif activity_level == 1:
            activity_level_change = percent_bmr_change - 0.03
        elif activity_level == 2:
            activity_level_change = percent_bmr_change - 0.02
        elif activity_level == 3:
            activity_level_change = percent_bmr_change
        elif activity_level == 4:
            activity_level_change = percent_bmr_change + 0.015
        elif activity_level == 5:
            activity_level_change = percent_bmr_change + 0.03

        # Adjust user calorie target based on user data
        calorie_target = round(bmr * activity_level_change)

        # Create Macro Profile
        if goal == 1 and activity_level <= 2:
            protein_adjustment = 0.8
        elif goal == 1 and activity_level >= 3:
            protein_adjustment = 1
        if goal == 2 and activity_level <= 2:
            protein_adjustment = 1
        elif goal == 2 and activity_level >= 3:
            protein_adjustment = 1.2
        if goal == 3 and activity_level <= 2:
            protein_adjustment = 0.9
        elif goal == 3 and activity_level >= 3:
            protein_adjustment = 1.1

        # Calculate macros
        total_protein = (weight * protein_adjustment) * 4
        protein_percent = total_protein / calorie_target
        remaining_percent = 1 - protein_percent
        carb_adjustment = remaining_percent * 0.75
        fat_adjustment = remaining_percent * 0.25

        protein = round(weight * protein_adjustment)
        carbs = round((carb_adjustment * calorie_target) / 4)
        fats = round((fat_adjustment * calorie_target) / 9)

        # Check that all macros add up to 1
        total_adjustment = protein_percent + carb_adjustment + fat_adjustment

        # Get Program Type
        if time_commitment == 1:
            program = "Full Body Program"
        elif time_commitment == 2:
            program = "Upper/Lower"
        elif time_commitment == 3:
            program = "PPL (5 days)"
        elif time_commitment == 4:
            program = "PPL (6 days)"

        # Create a FitnessProfile object and save it to the database
        fitness_profile = {
            'name':name,
            'age':age,
            'height':height,
            'weight':weight,
            'goal':goal,
            'activity_level':activity_level,
            'time_commitment':time_commitment,
            'calorie_target':calorie_target,
            'protein':protein,
            'carbs':carbs,
            'fats':fats,
            'program':program
        }
        

        # Create context dictionary
        context = {
            'fitness_profile': fitness_profile
        }
        if 'fitness_profile' in request.session:
            del request.session['fitness_profile']
        

        return render(request, 'fitness/input_form.html', context)

    return render(request, 'fitness/input_form.html')

fitnessProject/fitnessApp/templates/fitness/fitness_profile.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'fitness/style.css' %}"/>
{% if fitness_profile_data %}
    <div class="profile">
        <h1>Your Fitness Profile!</h1>
        <hr>
        <p>Target Daily Calories: {{ calorie_target }}</p>
        <p>Protein Recommendation (grams): {{ protein }}</p>
        <p>Carb Recommendation (grams): {{ carbs }}</p>
        <p>Fat Recommendation (grams): {{ fats }}</p>
        <hr>
        <h2>Your Program</h2>
        <p>{{ program }}</p>
    </div>
{% endif %}

fitnessProject/fitnessApp/templates/fitness/input_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'fitness/style.css' %}"/>
<head>
    <title>Fitness AI Assistant</title>
</head>
<body>
    <section class="header">
        <h1>Fitness AI Assistant</h1>
    </section>
    <div class="container">
        <form class="input_form" method="post" action="{% url 'fitness:fitness_profile' %}">
            {% csrf_token %}
            <label for="name">Name:</label>
            <input type="text" name="name"><br>
            <label for="age">Age:</label>
            <input type="number" name="age"><br>
            <label for="height">Height in inches:</label>
            <input type="number" name="height"><br>
            <label for="weight">Weight in lbs:</label>
            <input type="number" name="weight"><br>
            <label for="goal">What is your fitness goal?</label>
            <select name="goal">
                <option value="1">Lose Fat</option>
                <option value="2">Gain Muscle</option>
                <option value="3">Gain Muscle and Lose Fat</option>
            </select><br>
            <label for="activity_level">What activity level can you commit to?</label>
            <select name="activity_level">
                <option value="0">Sedentary (No Exercise)</option>
                <option value="1">Occasional (Exercise once every 2 weeks for approx 30 min)</option>
                <option value="2">Light (Exercise once a week for approx 30 min)</option>
                <option value="3">Average (Exercise 2-3 times a week for approx 1-3 hours)</option>
                <option value="4">Daily (Exercise daily for approx 4-7 hrs)</option>
                <option value="5">Advanced (Intense daily exercise for approx 7-14 hrs)</option>
            </select><br>
            <label for="time_commitment">How much time can you commit to working out each week?</label>
            <select name="time_commitment">
                <option value="1">3 Days/week</option>
                <option value="2">4 Days/week</option>
                <option value="3">5 Days/week</option>
                <option value="4">6 Days/week</option>
            </select><br>
            <input class="submit_button" type="submit" value="Submit">
        </form>

        {% if fitness_profile %}
            <div class="profile">
                <h1>Your Fitness Profile!</h1>
                <hr>
                <p>Target Daily Calories: {{ fitness_profile.calorie_target }}</p>
                <p>Protein Recommendation (grams): {{ fitness_profile.protein }}</p>
                <p>Carb Recommendation (grams): {{ fitness_profile.carbs }}</p>
                <p>Fat Recommendation (grams): {{ fitness_profile.fats }}</p>
                <hr>
                <h2>Your Program</h2>
                <p>{{ fitness_profile.program }}</p>
            </div>
        {% endif %}
    </div>
</body>